# Generated by Django 5.2.1 on 2025-08-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='store',
            name='image_data',
            field=models.TextField(blank=True, null=True, verbose_name='お店の画像（Base64）'),
        ),
    ]
