# Generated by Django 5.2.1 on 2025-08-21 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_store_image_store_image_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('good', '👍 ぐっと'), ('bad', '👎 のっと'), ('question', '❓ ？')], max_length=20, verbose_name='リアクション')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='リアクション日')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reviews.review', verbose_name='レビュー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='リアクションした人')),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
