# Generated by Django 5.2.1 on 2025-07-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '最高'), (4, '良好'), (3, '普通'), (2, '微妙'), (1, '最低')], default=3, verbose_name='評価'),
        ),
    ]
