# Generated by Django 5.2.1 on 2025-07-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '😍 文句なしの大満足！'), (4, '✨ かなり良い'), (3, '🙂 まあまあ'), (2, '🤔 うーん…'), (1, '😩 がっかり…')], default=3, verbose_name='評価'),
        ),
    ]
