# Generated by Django 5.2.1 on 2025-08-22 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_notification_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('color', models.CharField(choices=[('#FF6B6B', '赤'), ('#4ECDC4', '青緑'), ('#45B7D1', '青'), ('#96CEB4', '緑'), ('#FFEAA7', '黄'), ('#DDA0DD', '紫'), ('#F39C12', 'オレンジ'), ('#E17055', '茶'), ('#74B9FF', '水色'), ('#FD79A8', 'ピンク')], default='#4ECDC4', max_length=7, verbose_name='色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.ManyToManyField(blank=True, to='reviews.tag', verbose_name='タグ'),
        ),
    ]
