# Generated by Django 5.2.1 on 2025-08-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_tag_store_tags'),
    ]

    operations = [
    ]
