# Generated by Django 5.2.1 on 2025-08-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20250822_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終使用日'),
        ),
    ]
