# Generated by Django 5.2.1 on 2025-08-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20250822_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
