# Generated by Django 5.2.1 on 2025-08-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_store_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='公式サイトURL'),
        ),
    ]
